import type { Course } from '../types'

export const demoCourses: Course[] = [
  { id: 'python-projects', title: 'Programmer en Python: les bases par la pratique', description: 'Apprenez a programmer en construisant vos premiers projets.', category: 'programmation', level: 'debutant', duration_hours: 8, lectures_count: 29, price: 385, is_free: false, image_url: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=700&q=80', instructor_name: 'Ilyes Academy', rating: 4.9, students_count: 246, created_at: '2026-02-01' },
  { id: 'maths-visual', title: 'Mathematiques essentielles', description: 'Comprendre les notions essentielles avec une approche concrete.', category: 'mathematiques', level: 'intermediaire', duration_hours: 8, lectures_count: 29, price: 420, is_free: false, image_url: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=700&q=80', instructor_name: 'Ilyes Academy', rating: 4.9, students_count: 183, created_at: '2026-02-02' },
  { id: 'robotics-start', title: 'Robotique: construire son premier robot', description: 'Des capteurs au code, donnez vie a un projet complet.', category: 'robotique', level: 'debutant', duration_hours: 8, lectures_count: 29, price: 295, is_free: false, image_url: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=700&q=80', instructor_name: 'Ilyes Academy', rating: 4.9, students_count: 211, created_at: '2026-02-03' },
  { id: 'maths-free', title: 'Fondamentaux de mathematiques', description: 'Une remise a niveau progressive et accessible a tous.', category: 'mathematiques', level: 'debutant', duration_hours: 8, lectures_count: 29, price: 0, is_free: true, image_url: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=700&q=80', instructor_name: 'Ilyes Academy', rating: 4.9, students_count: 322, created_at: '2026-02-04' },
  { id: 'web-studio', title: 'Creer son premier site web', description: 'HTML, CSS et JavaScript dans un atelier guide.', category: 'programmation', level: 'intermediaire', duration_hours: 8, lectures_count: 29, price: 136, is_free: false, image_url: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=700&q=80', instructor_name: 'Ilyes Academy', rating: 4.9, students_count: 154, created_at: '2026-02-05' },
  { id: 'ai-robotics', title: 'Intelligence artificielle et robotique', description: 'Explorez les modeles intelligents a travers des prototypes.', category: 'robotique', level: 'avance', duration_hours: 8, lectures_count: 29, price: 237, is_free: false, image_url: 'https://images.unsplash.com/photo-1535378917042-10a22c95931a?auto=format&fit=crop&w=700&q=80', instructor_name: 'Ilyes Academy', rating: 4.9, students_count: 88, created_at: '2026-02-06' },
]
