import { useEffect, useState } from 'react'
import { ArrowRight, Award, BookOpen, Bot, CheckCircle2, Code2, Compass, Play, Quote, Sigma, Star } from 'lucide-react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import type { Course } from '../types'
import { demoCourses } from '../lib/courseData'
import heroArtwork from '../assetss/image.png'
import subjectArtwork from '../assetss/31860448-fef2-43c1-a8fe-36ef95159cc1.png'
import founderArtwork from '../assetss/be90a99d-de42-47cb-90c3-38561958a109.png'
import CourseCard from '../components/CourseCard'
import Layout from '../components/Layout'

const subjects = [
  { key: 'mathematiques', label: 'Mathematiques', icon: Sigma, text: 'Des bases solides jusqu au bac, avec une methode claire.', color: 'text-(--color-blue)' },
  { key: 'programmation', label: 'Programmation', icon: Code2, text: 'Python, web et algorithmique a travers des projets.', color: 'text-(--color-mint)' },
  { key: 'robotique', label: 'Robotique', icon: Bot, text: 'Capteurs, moteurs et IA pour donner vie a vos idees.', color: 'text-(--color-amber)' },
]

const steps = [
  { icon: Compass, title: 'Trouvez votre parcours', text: 'Choisissez la matiere et le niveau qui correspondent a votre prochain objectif.' },
  { icon: BookOpen, title: 'Apprenez en pratiquant', text: 'Des lecons courtes, des exercices guides et des projets concrets.' },
  { icon: Award, title: 'Mesurez vos progres', text: 'Suivez votre progression et construisez un portfolio de competences.' },
]

const stories = [
  { name: 'Sara Ben Ali', role: 'Eleve en programmation', text: 'Les exercices sont tres clairs. J ai cree mon premier site apres quelques semaines.', color: 'bg-[#dff7e8]' },
  { name: 'Youssef Mansour', role: 'Passionne de robotique', text: 'La theorie devient un vrai projet que l on peut montrer autour de soi.', color: 'bg-[#fff0d8]' },
  { name: 'Meriem Trabelsi', role: 'Eleve en mathematiques', text: 'Je comprends mieux les notions et je sais exactement quoi travailler.', color: 'bg-[#dff7f1]' },
]

const articles = [
  { category: 'Programmation', title: 'Pourquoi apprendre Python quand on debute ?', image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=900&q=80' },
  { category: 'Robotique', title: 'Construire son premier projet avec des capteurs', image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=900&q=80' },
  { category: 'Methode', title: 'Les 4 habitudes des eleves qui progressent', image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=900&q=80' },
]

export default function Home() {
  const [courses, setCourses] = useState<Course[]>([])

  useEffect(() => {
    supabase.from('courses').select('*').order('created_at', { ascending: false }).limit(6)
      .then(({ data }) => setCourses((data as Course[]) ?? []))
  }, [])

  return (
    <Layout>
      <section className="relative overflow-hidden min-h-[760px] bg-[#eefaf2] bg-cover bg-center border-b border-(--color-line)" style={{ backgroundImage: `linear-gradient(90deg, rgba(238,250,242,.96) 0%, rgba(238,250,242,.82) 42%, rgba(238,250,242,.08) 76%), url(${heroArtwork})` }}>
        <div className="absolute inset-0 bg-gradient-to-r from-[#eefaf2]/35 via-transparent to-transparent" />
        <div className="absolute -right-24 -top-20 h-96 w-96 blob-blue opacity-50" />
        <div className="relative max-w-7xl mx-auto px-5 md:px-8 pt-16 md:pt-24 pb-20 grid lg:grid-cols-[1.03fr_.97fr] gap-14 items-center">
          <div>
            <span className="inline-flex items-center gap-2 rounded-full bg-white border border-(--color-line) px-4 py-2 text-xs font-bold text-(--color-blue) shadow-sm"><span className="w-2 h-2 rounded-full bg-(--color-amber)" /> La nouvelle generation apprend ici</span>
            <h1 className="font-display font-extrabold text-4xl md:text-6xl leading-[1.08] tracking-tight mt-7 max-w-2xl">Master Math, <span className="text-(--color-blue)">Programming</span> &amp; Robotics</h1>
            <p className="mt-6 text-(--color-muted) text-lg max-w-xl leading-relaxed">Interactive courses, hands-on projects and expert support to help you build real skills for the future.</p>
            <div className="flex flex-wrap gap-5 mt-7 text-sm font-semibold text-[#102b46]"><span className="inline-flex items-center gap-2"><span className="w-9 h-9 rounded-full bg-(--color-blue) text-white flex items-center justify-center">+−</span> Mathematics</span><span className="inline-flex items-center gap-2"><span className="w-9 h-9 rounded-full bg-[#4778e8] text-white flex items-center justify-center">&lt;/&gt;</span> Programming</span><span className="inline-flex items-center gap-2"><span className="w-9 h-9 rounded-full bg-[#8156d8] text-white flex items-center justify-center">●</span> Robotics</span></div>
            <div className="mt-8 flex flex-wrap gap-4"><Link to="/courses" className="btn-primary inline-flex items-center gap-2 rounded-full bg-(--color-blue) px-7 py-4 font-bold text-white">Commencer un cours <ArrowRight size={18} /></Link><Link to="/about" className="inline-flex items-center gap-2 rounded-full border border-(--color-line) bg-white px-7 py-4 font-bold hover:border-(--color-blue)"><Play size={16} fill="currentColor" /> Decouvrir Academy</Link></div>
            <div className="mt-12 flex flex-wrap gap-8">{[['2.4k+', 'eleves actifs'], ['38', 'parcours pratiques'], ['4.9/5', 'satisfaction']].map(([value, label]) => <div key={label}><p className="font-display font-extrabold text-2xl">{value}</p><p className="text-sm text-(--color-muted) mt-1">{label}</p></div>)}</div>
          </div>
          <div className="relative min-h-[560px] flex items-center justify-center lg:opacity-0 lg:pointer-events-none"><div className="absolute right-0 top-8 w-96 h-96 rounded-full bg-[#dff4e5]" /><div className="absolute left-0 bottom-10 w-40 h-40 rounded-full border-2 border-(--color-blue)/30" /><div className="relative w-full max-w-[510px] h-[530px] overflow-hidden rounded-[3rem] border-8 border-white shadow-blue"><img src="https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1100&q=90" alt="Student learning programming on a laptop" className="h-full w-full object-cover object-center" /><div className="absolute top-8 left-6 rounded-2xl bg-white/95 p-4 shadow-lg rotate-[-6deg] text-(--color-blue) font-display font-bold text-lg">a² + b² = c²</div><div className="absolute top-20 right-5 rounded-2xl bg-white/95 p-4 shadow-lg rotate-[6deg] text-(--color-blue)"><Bot size={34} /></div><div className="absolute bottom-5 left-5 right-5 rounded-2xl bg-white/95 backdrop-blur p-4 flex items-center gap-3 shadow-lg"><div className="w-10 h-10 rounded-xl bg-[#fff0d8] flex items-center justify-center text-(--color-amber)"><CheckCircle2 size={21} /></div><div><p className="font-display font-bold text-sm">Learning by building</p><p className="text-xs text-(--color-muted)">A real project at every step</p></div></div></div><div className="absolute z-10 left-0 top-28 rounded-full w-32 h-32 bg-(--color-blue) text-white flex flex-col items-center justify-center text-center shadow-blue"><BookOpen size={22} /><strong className="font-display text-2xl">1,235</strong><span className="text-xs">courses</span></div><div className="absolute z-10 right-0 top-4 rounded-full w-32 h-32 bg-white text-(--color-blue) flex flex-col items-center justify-center text-center shadow-blue"><strong className="font-display text-2xl">4.8 <Star size={16} fill="currentColor" className="inline" /></strong><span className="text-xs text-(--color-muted)">Rating (86K)</span></div></div>
        </div>
      </section>
      <section className="relative w-full min-h-[620px] bg-cover bg-center" style={{ backgroundImage: `url(${subjectArtwork})` }}><div className="absolute inset-0 grid md:grid-cols-3">{subjects.map(({ key, label }) => <Link key={key} to={`/courses?category=${key}`} className="group relative flex items-end justify-center p-8 hover:bg-white/10 transition-colors"><span className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-bold text-(--color-blue) shadow-lg">Explorer {label} <ArrowRight size={16} className="group-hover:translate-x-1" /></span></Link>)}</div></section>
      <section className="relative overflow-hidden bg-[#f7fcf8] border-y border-(--color-line)"><div className="absolute -left-24 top-24 w-64 h-64 rounded-full bg-[#dff7e8] blur-3xl opacity-70" /><div className="absolute -right-24 bottom-10 w-72 h-72 rounded-full bg-[#fff0d8] blur-3xl opacity-70" /><div className="relative max-w-7xl mx-auto px-5 md:px-8 py-20"><div className="flex items-end justify-between gap-6 mb-10"><div><span className="inline-flex items-center gap-2 rounded-full bg-white border border-(--color-line) px-4 py-2 text-xs font-bold text-(--color-blue) shadow-sm"><span className="w-2 h-2 rounded-full bg-(--color-amber)" /> Learn by doing</span><h2 className="font-display font-extrabold text-3xl md:text-4xl mt-5 text-[#102b46]">Nos parcours pour <span className="text-(--color-blue)">avancer</span></h2><p className="text-(--color-muted) mt-3 max-w-xl">Des cours pratiques, des projets concrets et une progression visible a chaque etape.</p></div><Link to="/courses" className="hidden sm:inline-flex items-center gap-2 rounded-full bg-(--color-blue) text-white px-5 py-3 text-sm font-bold shadow-blue">Voir le catalogue <ArrowRight size={16} /></Link></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">{[...courses, ...demoCourses].filter((course, index, all) => all.findIndex((item) => item.id === course.id) === index).slice(0, 6).map((course) => <CourseCard key={course.id} course={course} />)}</div></div></section>
      <section className="max-w-7xl mx-auto px-5 md:px-8 py-20 grid lg:grid-cols-[.82fr_1.18fr] gap-14 items-center"><div className="relative"><div className="absolute inset-4 rounded-[2.5rem] bg-[#fff0d8] -rotate-3" /><img src="https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&w=1000&q=85" alt="Projet de robotique" className="relative rounded-[2.5rem] h-[390px] w-full object-cover shadow-blue" /></div><div><p className="text-sm font-bold text-(--color-blue) mb-3">Une methode qui reste</p><h2 className="font-display font-extrabold text-3xl md:text-4xl leading-tight">Chaque lecon vous rapproche d un projet reel.</h2><p className="text-(--color-muted) leading-relaxed mt-5 max-w-xl">Pas de cours interminables. Nos enseignants decoupent les concepts, puis vous aident a les transformer en quelque chose de concret.</p><div className="grid sm:grid-cols-3 gap-6 mt-9">{steps.map(({ icon: Icon, title, text }, index) => <div key={title}><div className="flex items-center gap-3"><span className="w-9 h-9 rounded-xl bg-[#eaf2ff] text-(--color-blue) flex items-center justify-center font-bold">0{index + 1}</span><Icon size={18} className="text-(--color-blue)" /></div><h3 className="font-display font-bold mt-4">{title}</h3><p className="text-sm text-(--color-muted) leading-relaxed mt-2">{text}</p></div>)}</div></div></section>
      <section className="relative min-h-[650px] overflow-hidden bg-[#eefaf2] bg-cover bg-center" style={{ backgroundImage: `url(${founderArtwork})` }}><div className="relative max-w-7xl mx-auto px-5 md:px-8 py-24 grid lg:grid-cols-2 items-center"><div className="lg:col-start-1 lg:justify-self-start max-w-xl text-left"><span className="inline-flex rounded-full bg-white border border-[#cfe9d7] px-4 py-2 text-xs font-bold tracking-[.15em] text-(--color-blue)">LE FONDATEUR</span><h2 className="font-display font-extrabold text-4xl md:text-6xl leading-[1.08] text-[#102b46] mt-7">A propos de<br />votre <span className="text-(--color-blue)">formateur</span></h2><p className="text-(--color-muted) leading-relaxed mt-6 max-w-md">Passionne par l education et les nouvelles technologies, je construis des cours accessibles, pratiques et progressifs pour aider chaque eleve a prendre confiance.</p><div className="flex flex-wrap gap-3 mt-7">{[['Σ', 'Mathematiques', 'bg-[#69c58c]'], ['&lt;/&gt;', 'Programmation', 'bg-[#4778e8]'], ['●', 'Robotique', 'bg-[#8156d8]']].map(([icon, label, color]) => <span key={label} className="inline-flex items-center gap-2 rounded-full bg-white border border-[#cfe9d7] px-3 py-2 text-sm font-semibold text-[#102b46]"><span className={`w-8 h-8 rounded-full ${color} text-white flex items-center justify-center`} dangerouslySetInnerHTML={{ __html: icon }} />{label}</span>)}</div><Link to="/about" className="btn-primary inline-flex items-center gap-2 rounded-full bg-(--color-blue) text-white px-7 py-4 font-bold mt-8">Decouvrir mon parcours <ArrowRight size={17} /></Link><p className="font-display italic text-2xl text-(--color-blue) mt-8">Apprendre aujourd hui,<br />creer demain.</p></div></div></section>
      <section className="max-w-7xl mx-auto px-5 md:px-8 py-20"><div className="text-center max-w-2xl mx-auto"><p className="text-sm font-bold text-(--color-blue) mb-2">Ils avancent avec nous</p><h2 className="font-display font-extrabold text-3xl md:text-4xl">Des progres qui se ressentent</h2></div><div className="grid md:grid-cols-3 gap-6 mt-10">{stories.map((story) => <article key={story.name} className="rounded-2xl border border-(--color-line) bg-white p-7"><Quote size={26} className="text-(--color-blue-light)" /><p className="text-(--color-muted) leading-relaxed mt-5">&quot;{story.text}&quot;</p><div className="flex items-center gap-3 mt-7"><div className={`w-11 h-11 rounded-full ${story.color} flex items-center justify-center font-display font-bold text-(--color-blue)`}>{story.name.split(' ').map((part) => part[0]).join('')}</div><div><p className="font-display font-bold text-sm">{story.name}</p><p className="text-xs text-(--color-muted)">{story.role}</p></div><div className="ml-auto flex text-(--color-amber)"><Star size={13} fill="currentColor" /><Star size={13} fill="currentColor" /><Star size={13} fill="currentColor" /><Star size={13} fill="currentColor" /><Star size={13} fill="currentColor" /></div></div></article>)}</div></section>
      <section className="relative overflow-hidden border-t border-[#d7f0df]" style={{ background: 'radial-gradient(circle at 8% 18%, rgba(184,239,207,.42), transparent 28%), radial-gradient(circle at 92% 78%, rgba(184,239,207,.38), transparent 30%), linear-gradient(135deg, #f5fff8 0%, #eafbf3 100%)' }}><div className="absolute -left-24 -top-20 w-80 h-80 rounded-[45%] bg-[#ddf7e7]/70 blur-2xl" /><div className="absolute right-[-5rem] top-20 w-72 h-72 rounded-full border border-(--color-blue)/15" /><div className="absolute right-20 bottom-10 w-48 h-48 rounded-full bg-white/35 blur-xl" /><div className="absolute left-12 bottom-16 w-24 h-24 rounded-[45%] border border-(--color-blue)/20 rotate-12" /><div className="absolute left-8 top-28 flex gap-2 rotate-[-18deg]" aria-hidden="true"><span className="w-2 h-7 rounded-full bg-(--color-amber)" /><span className="w-2 h-5 rounded-full bg-(--color-amber) mt-3" /><span className="w-2 h-7 rounded-full bg-(--color-amber)" /></div><div className="relative max-w-7xl mx-auto px-5 md:px-8 py-20"><div className="flex items-end justify-between gap-6 mb-10"><div><p className="text-sm font-bold text-(--color-blue) mb-2">Le journal Academy</p><h2 className="font-display font-extrabold text-3xl md:text-4xl text-[#102b46]">Idees, conseils et inspiration</h2></div><Link to="/blog" className="hidden sm:inline-flex items-center gap-2 rounded-full bg-white/80 border border-white px-5 py-3 text-sm font-bold text-(--color-blue) shadow-sm">Tous les articles <ArrowRight size={16} /></Link></div><div className="grid md:grid-cols-3 gap-6">{articles.map((article) => <Link to="/blog" key={article.title} className="group rounded-2xl overflow-hidden bg-white/90 border border-white/80 hover:shadow-blue hover:-translate-y-1 transition-all"><img src={article.image} alt="" className="h-48 w-full object-cover group-hover:scale-105 transition-transform duration-500" /><div className="p-6"><p className="text-xs font-bold text-(--color-blue)">{article.category}</p><h3 className="font-display font-bold text-lg mt-3 leading-snug text-[#102b46]">{article.title}</h3><span className="inline-flex items-center gap-2 text-sm font-bold text-(--color-blue) mt-5">Lire l article <ArrowRight size={15} /></span></div></Link>)}</div></div></section>
    </Layout>
  )
}